### ISSUE TITLE
Reads from the device seem to fail

### ISSUE THREAD

**Issue by drtimf** [CoreElectronics/CE-PiicoDev-RGB-LED-MicroPython-Module#1]
I have been implementing a driver in Go for this LED module and I am finding all read requests from the device fail with an I/O error.  I have executed the firmware version and device ID requests in Python and they seem to fail as well.  For example, readFirmware():

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    print(leds.readFirmware())
  File "/home/pi/picodev/CE-PiicoDev-RGB-LED-MicroPython-Module/PiicoDev_RGB.py", line 53, in readFirmware
    v=self.i2c.readfrom_mem(self.addr, _regFirmVer, 2)
  File "/home/pi/picodev/CE-PiicoDev-RGB-LED-MicroPython-Module/PiicoDev_Unified.py", line 97, in readfrom_mem
    self.smbus_i2c_read(addr, memaddr, data, nbytes, addrsize=addrsize)
  File "/home/pi/picodev/CE-PiicoDev-RGB-LED-MicroPython-Module/PiicoDev_Unified.py", line 126, in smbus_i2c_read
    self.i2c.i2c_rdwr(msg_w, msg_r)
  File "/home/pi/.local/lib/python3.7/site-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 5] Input/output error

I would have thought, looking at the firmware implementation and the requestEvent(), you should be able to read anything in memory (there is no limit imposed, it seems).  I was hoping you could read the brightness back as well, for example.

Perhaps I am doing something wrong?

Looking at your buzzer firmware and implementing the Go driver for this, it seems this one works correctly.  I noticed it is newer and perhaps you have gained more firmware development experience? :)

**Comment by CoreProduction** [comment]
Thanks for raising this @drtimf - and apologies for the delay.
This is a known issue with the current firmware. 
Reads from the device work fine in MicroPython (Raspberry Pi Pico) but result in an error for Raspberry Pi.
The PiicoDev Buzzer firmware has an updated philosophy that works across all supported platforms.
Since the RGB module is really an output device, there's probably no need to execute any reads from it. I've removed the readID() function from the API docs.

We _could_ overhaul the firmware to upgrade it to the new method of I2C handling, but the risk of introducing new bugs probably outweighs the small gain in having access to a (often unused) ID.

New devices we release will of course make use of the updated I2C handling philosophy.
